### ISSUE TITLE
client.term_start_date doesn‘t work as expected.

### ISSUE THREAD

**Issue by Howard-Cao** [PhotonQuantum/pysjtu#11]
I was using the export.py script to create an iCalendar file of my latest semester. Everything worked fine except for the start day of the semester. 
`term_start = client.term_start_date`
I changed both the parameters of `client.schedule(2022, 0)` but the problem persisted. I later checked the variables in IDE's debug interface, and it seemed that the variable `term_start` was stucked at 2024-02-12 (I ran this script at 2024-2-18).
I concerned that there may be some logical erors in the codes behind the `client.term_start_date` stuff. I would be grateful if you fix that.

System: windows 10 22H2 IDE: VS Code, with Jupyter notebook add-on, core = python 3.9.10

**Comment by PhotonQuantum** [comment]
The term start date is extracted from i.sjtu.edu.cn, but it appears to be incorrect. The `schedule` API does not depend on `term_start_date`. As you can see in the `export.py` demo, you can manually specify a term start date to replace the scaped one.
